; vibrolab v1.5 · ESP32-S3 流式诊断 (LR+Bot-40, 双工况训练, 无自校准)
[platformio]
default_envs = esp32s3
src_dir = .

[env:esp32s3]
platform        = espressif32@^6.7.0
board           = esp32-s3-devkitc-1
framework       = arduino
monitor_speed   = 921600
upload_speed    = 921600
board_build.flash_size            = 16MB
board_build.arduino.memory_type   = qio_opi
board_build.partitions            = default.csv
build_flags = -O2 -DBOARD_HAS_PSRAM -std=gnu++17
build_src_filter = +<*.ino> +<*.c> +<*.h>
lib_deps =
  olikraus/U8g2 @ ^2.35          ; OLED 中文显示 (HAS_OLED=1 时需要)
