"""一键: CWRU 数据 → Bot-40 (Cohen's d 选维) → LR → model.h

跑一遍就完事. 输出 firmware_v1_5/model.h, 直接给 firmware_v1_5.ino 用.

用法:
  python firmware_v1_5/train_export_model.py
  python firmware_v1_5/train_export_model.py --no-export   # 只测精度, 不覆盖 model.h

前置:
  - CWRU 数据按 data/README.md 放好 (仓库内 data/), 或设 CWRU_DATA_ROOT 环境变量
  - pip install -r requirements.txt

产物:
  firmware_v1_5/model.h  — 硬件层直接 #include 就行

数值可复现: seed=42, 相同 CWRU 数据 + 相同代码 → 相同 model.h (逐字节).
"""
from __future__ import annotations
import os
import sys
import argparse
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, '..')))

from vibrolab import io as vio, features as vbf
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# ---- 参数 (改这里就可以复现不同实验) ----
WINDOW = 2048           # 窗长 (采样点). CWRU 12kHz -> 170ms/窗
STEP = 2048             # 步长 = 窗长, 无重叠, 避免数据泄漏
TRAIN_LOADS = [0, 3]    # 训练用哪些工况 (HP). 其他工况自动作为 held-out 验证
K_BOT = 40              # Bot-K: 选 Cohen's d 最小的 K 维
SEED = 42               # 可复现


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--no-export', action='store_true', help='只跑精度, 不覆盖 model.h')
    args = ap.parse_args()

    print('=' * 60)
    print(f'训练工况: {TRAIN_LOADS}HP    Bot-K: {K_BOT}    seed: {SEED}')
    held_out = [L for L in [0, 1, 2, 3] if L not in TRAIN_LOADS]
    print(f'验证工况: 全 4 工况 (held-out: {held_out}HP)')
    print('=' * 60)

    # ---- Step 1: 加载 + 提特征 ----
    print('\n[1/4] 加载 CWRU + 提 120 维 CFD 特征...')
    samples = vio.load_cwru(loads=[0, 1, 2, 3])
    X_raw, y, ld = vio.build_dataset(samples, window=WINDOW, step=STEP)
    X = vbf.extract_cfd(X_raw, fs=vio.FS_12K).astype(np.float32)
    print(f'  {len(X)} 窗, 120 维, 10 类, 4 工况')

    # ---- Step 2: Cohen's d 选 Bot-40 (跨训练工况的漂移量最小的 40 维) ----
    print(f"\n[2/4] Cohen's d 选 Bot-{K_BOT} (只用训练工况)...")
    X_a = X[ld == TRAIN_LOADS[0]]
    X_b = X[ld == TRAIN_LOADS[1]]
    d_full, ranked = vbf.prealign_select(X_a, X_b, method='cohen')
    bot40 = np.sort(vbf.select_low_drift(ranked, k=K_BOT))
    print(f'  选出维度: {bot40.tolist()}')
    print(f'  Cohen\'s d 范围: [{d_full[bot40].min():.4f}, {d_full[bot40].max():.4f}]')

    # ---- Step 3: 训 scaler + LR (只用训练工况) ----
    print('\n[3/4] StandardScaler + LR 训练 (仅训练工况)...')
    train_mask = np.isin(ld, TRAIN_LOADS)
    Xs, ys = X[train_mask][:, bot40], y[train_mask]
    sc = StandardScaler().fit(Xs)
    lr = LogisticRegression(max_iter=1000, C=1.0, random_state=SEED).fit(sc.transform(Xs), ys)

    # ---- Step 4: 全 4 工况精度 ----
    print('\n[4/4] 全 4 工况精度:')
    for L in [0, 1, 2, 3]:
        m = ld == L
        yp = lr.predict(sc.transform(X[m][:, bot40]))
        acc = accuracy_score(y[m], yp)
        tag = '训练工况' if L in TRAIN_LOADS else 'held-out'
        print(f'  {L}HP ({tag}): {acc*100:.2f}%  ({m.sum()} 窗)')

    # ---- 导出 model.h ----
    if args.no_export:
        print('\n[跳过导出] --no-export')
        return
    out = os.path.join(HERE, 'model.h')
    export_model_h(bot40, sc, lr, out)
    size_kb = os.path.getsize(out) / 1024
    print(f'\n导出 -> {out}')
    print(f'  文件大小: {size_kb:.1f} KB')
    print(f'  下一步: Arduino IDE 打开 firmware_v1_5/firmware_v1_5.ino, 编译上传即可.')


def export_model_h(bot40, sc, lr, out_path):
    """写 C 头文件. firmware_v1_5.ino 里 #include "model.h" 拿这些常量做推理."""
    n_cls = lr.coef_.shape[0]
    L = ['/* Auto-generated by firmware_v1_5/train_export_model.py — DO NOT EDIT. */',
         '#ifndef VIBROLAB_MODEL_H',
         '#define VIBROLAB_MODEL_H',
         '',
         f'#define VIBROLAB_FS         {vio.FS_12K}',
         f'#define VIBROLAB_WINDOW     {WINDOW}',
         f'#define VIBROLAB_N_CLASSES  {n_cls}',
         f'#define VIBROLAB_BOT40_K    {K_BOT}',
         '',
         '/* 英文类名 (给 stream_host.py 比对; OLED 中文标签在 firmware_v1_5.ino 里另定义) */',
         'static const char *VIBROLAB_LABEL_NAMES[] = {']
    L += [f'    "{n}",' for n in vio.LABEL_NAMES]
    L += ['};', '',
          f'static const int VIBROLAB_BOT40_INDICES[{K_BOT}] = {{',
          '    ' + ', '.join(str(int(i)) for i in bot40),
          '};', '',
          f'static const float VIBROLAB_SCALER_MEAN[{K_BOT}] = {{',
          '    ' + ', '.join(f'{v:.7g}f' for v in sc.mean_),
          '};',
          f'static const float VIBROLAB_SCALER_SCALE[{K_BOT}] = {{',
          '    ' + ', '.join(f'{v:.7g}f' for v in sc.scale_),
          '};', '',
          f'static const float VIBROLAB_LR_COEF[{n_cls}][{K_BOT}] = {{']
    for row in lr.coef_:
        L.append('    {' + ', '.join(f'{v:.7g}f' for v in row) + '},')
    L += ['};',
          f'static const float VIBROLAB_LR_INTERCEPT[{n_cls}] = {{',
          '    ' + ', '.join(f'{v:.7g}f' for v in lr.intercept_),
          '};',
          '',
          '#endif',
          '']
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L))


if __name__ == '__main__':
    main()
